In [ ]:
# SYSTEM OF NON LINEAR EQUATIONS
# equations given  in form of 2 or 3 variables

In [1]:
import numpy as np

In [2]:
#Non Linear euqtions
coeff_matrix = np.matrix("3,1,2;4,2,5;6,7,8")

In [3]:
coeff_matrix

matrix([[3, 1, 2],
        [4, 2, 5],
        [6, 7, 8]])

In [5]:
#Finding determinant of matrix
det_x = np.linalg.det(coeff_matrix)

In [6]:
det_x

-27.0

In [7]:
#Finding rank of a matrix 
rank_x = np.linalg.matrix_rank(coeff_matrix)

In [8]:
rank_x

3

In [11]:
#Finding inverse of a matrix 
inv_x = np.linalg.inv(coeff_matrix)

In [13]:
print(inv_x)

[[ 0.7037037  -0.22222222 -0.03703704]
 [ 0.07407407 -0.44444444  0.25925926]
 [-0.59259259  0.55555556 -0.07407407]]


In [14]:
ans_mat  = np.matrix("2;-1;3")

In [15]:
#return solution to the system Ax=b
#equator matrix
ans_final = np.linalg.solve(coeff_matrix,ans_mat)

In [16]:
ans_final

matrix([[ 1.51851852],
        [ 1.37037037],
        [-1.96296296]])

In [ ]:
# Sets: always unique elements
# dealing with multiple dataset
# training and testing data

In [ ]:
# remove the duplicacy item(s)
# noise in the form of duplicacy

In [7]:
friends = { "Milanjeet", 'Ayush' , 'Manjeet' , 'Abhay' , 'Tusshar' , 'Aditya'}

In [8]:
friends

{'Abhay', 'Aditya', 'Ayush', 'Manjeet', 'Milanjeet', 'Tusshar'}

In [3]:
#modify
friends.add('Manan')

In [4]:
friends

{'Abhay', 'Aditya', 'Ayush', 'Manan', 'Manjeet', 'Milanjeet', 'Tusshar'}

In [ ]:
#discard

In [9]:
friends.discard("Manan")

In [10]:
friends

{'Abhay', 'Aditya', 'Ayush', 'Manjeet', 'Milanjeet', 'Tusshar'}

In [ ]:
#clear

In [12]:
old_friends = friends

In [13]:
old_friends

{'Abhay', 'Aditya', 'Ayush', 'Manjeet', 'Milanjeet', 'Tusshar'}

In [14]:
friends

{'Abhay', 'Aditya', 'Ayush', 'Manjeet', 'Milanjeet', 'Tusshar'}

In [15]:
friends.clear()

In [16]:
friends

set()

In [17]:
old_friends

set()

In [ ]:
#set operations

In [18]:
friend_one = {"Ram" , "Mohan" , "Sohan" , "Geeta"}

In [19]:
friend_two = {"shyam" , "Sohan" , "Rohan" , "reeta"}

In [21]:
#union of sets
friend_one.union(friend_two)

{'Geeta', 'Mohan', 'Ram', 'Rohan', 'Sohan', 'reeta', 'shyam'}