<a href="https://colab.research.google.com/github/Ankit4725/Machine-learning/blob/main/First_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.matrix("2,1,6;1,0,1;3,1,3")
x

matrix([[2, 1, 6],
        [1, 0, 1],
        [3, 1, 3]])

In [ ]:
y = np.matrix("2;3;-1")
y

matrix([[ 2],
        [ 3],
        [-1]])

In [ ]:
print(x)

[[2 1 2]
 [1 0 1]
 [3 1 3]]


In [ ]:
print(y)

[[ 2]
 [ 3]
 [-1]]


In [ ]:
#Finding determinant of matrix x 
det_x = np.linalg.det(x)
print(det_x)

4.0


In [ ]:
det_y = np.linalg.det(y)
det_y

LinAlgError: ignored